services:
  db:
    image: postgres:16.3
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gopaper
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  go-paper:
    image: ml/go-paper
    build: ./server
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - VERSION=0.0.1
      - ADDR=:8080
      - DB_ADDR=postgres://admin:admin@db:5432/gopaper?sslmode=disable

volumes:
  db-data:
